name: flutter_geofence
description: Plugin to interact with geofences, and get the user's current/latest location.
version: 0.4.0
homepage: https://github.com/DwayneCoussement/geofence

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.intivoto.geofence
        pluginClass: GeofencePlugin
      ios:
        pluginClass: GeofencePlugin